-- Nasty Burger House customer platform schema
--
-- The canonical production schema now lives at:
--   supabase/migrations/202609050001_customer_platform.sql
--
-- That migration includes Supabase Auth integration, customer/admin RLS,
-- server-owned orders, Drip Points lifecycle rules, reviews and admin access.
-- Apply the migration from the Supabase SQL editor or Supabase CLI instead of
-- maintaining a second copy of the schema here.
