create table if not exists public.admin_audit_log (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references auth.users(id) on delete set null,
  action text not null check (char_length(action) between 1 and 120),
  target_type text not null check (char_length(target_type) between 1 and 80),
  target_id text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.admin_audit_log enable row level security;

revoke all on table public.admin_audit_log from public, anon, authenticated;
grant select, insert on table public.admin_audit_log to service_role;
grant usage, select on sequence public.admin_audit_log_id_seq to service_role;

drop policy if exists admin_audit_log_deny_browser on public.admin_audit_log;
create policy admin_audit_log_deny_browser
on public.admin_audit_log
for all
to anon, authenticated
using (false)
with check (false);

create index if not exists admin_audit_log_actor_created_idx
  on public.admin_audit_log(actor_user_id, created_at desc);

create index if not exists admin_audit_log_target_idx
  on public.admin_audit_log(target_type, target_id, created_at desc);
